version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${MATCHLOG_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MATCHLOG_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MATCHLOG_POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - matchlog-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MATCHLOG_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MATCHLOG_MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - matchlog-network

  migrate:
    image: webapp
    build: ./
    depends_on:
      - postgres
    # 마이그레이션 수행 후 컨테이너 종료
    command: alembic upgrade head
    restart: "no"
    volumes:
      - "./:/code/"
    networks:
      - matchlog-network

  webapp:
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    build: ./
    image: webapp
    ports:
      - "8001:8000"
    volumes:
      - "./:/code"
      - "./keys:/app/keys"
    command: uvicorn webapp.application:app --host 0.0.0.0 --port 8000
    environment:
      - CONFIG_PATH=${MATCHLOG_CONFIG_PATH}
    restart: unless-stopped
    networks:
      - matchlog-network

volumes:
  postgres_data:
  mongodb_data:


networks:
  matchlog-network:
    driver: bridge
