version: "3.8"

services:
  frontend-admin:
    build:
      # Build context를 frontend 디렉토리로 설정 (monorepo 루트)
      context: ../../
      dockerfile: apps/admin/Dockerfile
      args:
        # 빌드 시점에서는 표준 REACT_APP_ 접두사 사용
        REACT_APP_SERVER_URI: ${REACT_APP_MOIMJANG_SERVER_URI:-http://localhost:8080}
        REACT_APP_NODE_ENV: ${REACT_APP_MOIMJANG_NODE_ENV:-development}
        REACT_APP_DANGEROUSLY_DISABLE_HOST_CHECK: ${REACT_APP_MOIMJANG_DANGEROUSLY_DISABLE_HOST_CHECK:-true}
        REACT_APP_ENVIRONMENT: ${REACT_APP_MOIMJANG_ENVIRONMENT:-local}
        REACT_APP_SITE_URL: ${REACT_APP_MOIMJANG_SITE_URL:-http://localhost:3000}
    container_name: moimjang-frontend-admin
    image: moimjang/frontend/admin:latest
    ports:
      - "3000:80"
    restart: unless-stopped
