export enum ChannelFeatureButton {
  GROUP = "GROUP",
  QUESTION_CARD = "QUESTION_CARD",
  MATCHLOG = "MATCHLOG",
  REVIEW_FORM = "REVIEW_FORM",
  REVIEW_LIST = "REVIEW_LIST",
  WRITE_REVIEW = "WRITE_REVIEW",
}
