export const GET_CHANNEL_LIST = "GET_CHANNEL_LIST";
export const GET_BRAND_BY_ID = "GET_BRAND_BY_ID";
export const GET_CHANNELS_BY_ID = "GET_CHANNELS_BY_ID";
export const GET_GROUPS = "GET_GROUPS";
export const GET_MATCHED_USER = "GET_MATCHED_USER";
export const GET_QUESTION_CATEGORIES = "GET_QUESTION_CATEGORIES";
export const GET_REVIEW_LIST = "GET_REVIEW_LIST";
export const GET_MY_INFO = "GET_MY_INFO";
