export const GET_CHANNEL_LIST = "GET_CHANNEL_LIST";
export const GET_CHANNELS = "GET_CHANNELS";

export const GET_CHANNELS_BY_ID = "GET_CHANNELS_BY_ID";

export const GET_MATCHED_USER = "GET_MATCHED_USER";
export const GET_CHANNEL_JOINED_USERS = "GET_CHANNEL_JOINED_USERS";
export const GET_GAMES = "GET_GAMES";
export const GET_GROUPS = "GET_GROUPS";
export const GET_MY_INFO = "GET_MY_INFO";
export const GET_REVIEW = "GET_REVIEW";
