"""Add image of brandReview

Revision ID: 06f55ff73580
Revises: b7d90aa9762a
Create Date: 2025-04-17 07:31:07.050172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f55ff73580'
down_revision: Union[str, None] = 'b7d90aa9762a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'brand_reviews',
        sa.Column('is_display', sa.Boolean(), server_default=sa.text('false'), nullable=False)
    )
    op.drop_column('brand_reviews', 'id_display')
    op.add_column('images', sa.Column('brand_review_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_images_brand_review_id", 'images', 'brand_reviews', ['brand_review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_images_brand_review_id", 'images', type_='foreignkey')
    op.drop_column('images', 'brand_review_id')
    op.add_column('brand_reviews', sa.Column('id_display', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('brand_reviews', 'is_display')
    # ### end Alembic commands ###
