"""Add field to Channel for participants

Revision ID: 0fa2181c5332
Revises: a5bd15ab0b9b
Create Date: 2025-04-18 03:15:22.112867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa2181c5332'
down_revision: Union[str, None] = 'a5bd15ab0b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('min_participants', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('channels', sa.Column('max_participants', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('channels', sa.Column('meeting_location', sa.String(length=255), server_default=sa.text("'need to set'"), nullable=False))
    op.add_column('channels', sa.Column('location_link', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'location_link')
    op.drop_column('channels', 'meeting_location')
    op.drop_column('channels', 'max_participants')
    op.drop_column('channels', 'min_participants')
    # ### end Alembic commands ###
