"""Add decription on Brand

Revision ID: 1b3f70c34517
Revises: 9b24b11d8cfc
Create Date: 2025-03-12 09:11:21.260194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3f70c34517'
down_revision: Union[str, None] = '9b24b11d8cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'description')
    # ### end Alembic commands ###
