"""Change model for channel to brand

Revision ID: 2d2eb0c97def
Revises: 8d7aa72023e7
Create Date: 2025-04-18 10:50:50.075811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2eb0c97def'
down_revision: Union[str, None] = '8d7aa72023e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('min_participants', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('brands', sa.Column('max_participants', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('brands', sa.Column('meeting_location', sa.String(length=255), server_default=sa.text("'need to set'::character varying"), nullable=False))
    op.add_column('brands', sa.Column('location_link', sa.Text(), nullable=True))
    op.alter_column('channels', 'event_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('channels', 'max_participants')
    op.drop_column('channels', 'location_link')
    op.drop_column('channels', 'meeting_location')
    op.drop_column('channels', 'min_participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('min_participants', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('channels', sa.Column('meeting_location', sa.VARCHAR(length=255), server_default=sa.text("'need to set'::character varying"), autoincrement=False, nullable=False))
    op.add_column('channels', sa.Column('location_link', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('channels', sa.Column('max_participants', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.alter_column('channels', 'event_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('brands', 'location_link')
    op.drop_column('brands', 'meeting_location')
    op.drop_column('brands', 'max_participants')
    op.drop_column('brands', 'min_participants')
    # ### end Alembic commands ###
