"""Change channel model for FK relation to brands

Revision ID: 2f6bd712e781
Revises: 1b3f70c34517
Create Date: 2025-03-15 04:11:43.300153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6bd712e781'
down_revision: Union[str, None] = '1b3f70c34517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_channels_brand_id", 'channels', 'brands', ['brand_id'], ['id'])
    # ### 카테고리 값에 따라 brand_id 수동매핑
    op.execute("UPDATE channels SET brand_id = 10 WHERE category = '찐프제게더링'")
    
    op.drop_column('channels', 'category')
    op.alter_column('channels', 'brand_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint("fk_channels_brand_id", 'channels', type_='foreignkey')
    op.drop_column('channels', 'brand_id')
    # ### end Alembic commands ###
