"""Add channel_id Fk in survey

Revision ID: 4c50c2fcb358
Revises: caac58ce26e4
Create Date: 2025-04-21 05:34:28.978430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c50c2fcb358'
down_revision: Union[str, None] = 'caac58ce26e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_survey_responses_channel_id", 'survey_responses', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_survey_responses_channel_id", 'survey_responses', type_='foreignkey')
    op.drop_column('survey_responses', 'channel_id')
    # ### end Alembic commands ###
