"""Add brand,channel state

Revision ID: 5773efb242e6
Revises: 2d2eb0c97def
Create Date: 2025-04-19 03:26:01.375310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5773efb242e6'
down_revision: Union[str, None] = '2d2eb0c97def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('brand_state', sa.String(), server_default=sa.text("'ONGOING'"), nullable=False))
    op.add_column('channels', sa.Column('channel_state', sa.String(), server_default=sa.text("'PENDING'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'channel_state')
    op.drop_column('brands', 'brand_state')
    # ### end Alembic commands ###
