"""Add field socialing_duration to brand table

Revision ID: 5d3fcf6a06ce
Revises: 4c50c2fcb358
Create Date: 2025-04-24 00:31:36.709533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3fcf6a06ce'
down_revision: Union[str, None] = '4c50c2fcb358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('socialing_duration', sa.Integer(), server_default='-1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'socialing_duration')
    # ### end Alembic commands ###
