"""Add enum for questionCard

Revision ID: 7a89cca57d6c
Revises: 2f6bd712e781
Create Date: 2025-03-21 07:20:15.812388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a89cca57d6c'
down_revision: Union[str, None] = '2f6bd712e781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE channelcomponent ADD VALUE 'QUESTION_CARD' AFTER 'REVIEW_LIST'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
