"""make delete cascade on image

Revision ID: 7f0a736a27ff
Revises: b9a75c45fcef
Create Date: 2025-05-22 11:14:53.782122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0a736a27ff'
down_revision: Union[str, None] = 'b9a75c45fcef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_brands_thumbnail_image_id', 'brands', type_='foreignkey')
    op.create_foreign_key("fk_brands_thumbnail_image_id", 'brands', 'images', ['thumbnail_image_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_question_card_categories_cover_image_id', 'question_card_categories', type_='foreignkey')
    op.create_foreign_key("fk_question_card_categories_cover_image_id", 'question_card_categories', 'images', ['cover_image_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_question_cards_image_id', 'question_cards', type_='foreignkey')
    op.create_foreign_key("fk_question_cards_image_id", 'question_cards', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_question_cards_image_id", 'question_cards', type_='foreignkey')
    op.create_foreign_key('fk_question_cards_image_id', 'question_cards', 'images', ['image_id'], ['id'])
    op.drop_constraint("fk_question_card_categories_cover_image_id", 'question_card_categories', type_='foreignkey')
    op.create_foreign_key('fk_question_card_categories_cover_image_id', 'question_card_categories', 'images', ['cover_image_id'], ['id'])
    op.drop_constraint("fk_brands_thumbnail_image_id", 'brands', type_='foreignkey')
    op.create_foreign_key('fk_brands_thumbnail_image_id', 'brands', 'images', ['thumbnail_image_id'], ['id'])
    # ### end Alembic commands ###
