"""Add LandingPageSettings

Revision ID: 8a525d38c8f1
Revises: 5d3fcf6a06ce
Create Date: 2025-04-25 14:19:36.027515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a525d38c8f1'
down_revision: Union[str, None] = '5d3fcf6a06ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_page_settings',
    sa.Column('setting_key', sa.String(length=255), nullable=False, comment='설정 키 (예: main_image_id, gallery_image_ids)'),
    sa.Column('setting_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='설정 값 (메인 이미지 ID는 숫자, 갤러리 ID 목록은 JSON 배열)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('setting_key')
    )
    op.create_index(op.f('ix_landing_page_settings_setting_key'), 'landing_page_settings', ['setting_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landing_page_settings_setting_key'), table_name='landing_page_settings')
    op.drop_table('landing_page_settings')
    # ### end Alembic commands ###
