"""Change Enum Name for WRITE_REVIEW

Revision ID: 8d7aa72023e7
Revises: 0fa2181c5332
Create Date: 2025-04-18 05:20:42.999747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7aa72023e7'
down_revision: Union[str, None] = '0fa2181c5332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE channelcomponent RENAME VALUE 'WRTIE_REVIEW' TO 'WRITE_REVIEW';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###    
    # ### end Alembic commands ###
    pass
