"""Add Brands, Categories, questionCards table

Revision ID: 9b24b11d8cfc
Revises: ffffc0c54a8c
Create Date: 2025-03-10 09:39:25.450868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b24b11d8cfc'
down_revision: Union[str, None] = 'ffffc0c54a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thumbnailImagePath', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_card_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('coverImagePath', sa.String(), nullable=True),
    sa.Column('isDeckVisible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_question_card_categories',
    sa.Column('brandId', sa.Integer(), nullable=False),
    sa.Column('questionCardCategoryId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brandId'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['questionCardCategoryId'], ['question_card_categories.id'], ),
    sa.PrimaryKeyConstraint('brandId', 'questionCardCategoryId')
    )
    op.create_table('question_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardCategoryId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('imagePath', sa.String(), nullable=True),
    sa.Column('isCardVisible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cardCategoryId'], ['question_card_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_cards')
    op.drop_table('brand_question_card_categories')
    op.drop_table('question_card_categories')
    op.drop_table('brands')
    # ### end Alembic commands ###
