"""Add Feild to reviews

Revision ID: 9e7763fe6824
Revises: fa7a8e09e54c
Create Date: 2025-02-25 06:22:03.102997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7763fe6824'
down_revision: Union[str, None] = 'fa7a8e09e54c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'keywords')
    # ### end Alembic commands ###
