"""Add Enum WRTIE_REVIEW

Revision ID: a5bd15ab0b9b
Revises: 06f55ff73580
Create Date: 2025-04-18 02:38:44.945003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5bd15ab0b9b'
down_revision: Union[str, None] = '06f55ff73580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE channelcomponent ADD VALUE 'WRTIE_REVIEW' AFTER 'QUESTION_CARD'")
    # ### end Alembic commands ###
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE channelcomponent DROP VALUE 'WRTIE_REVIEW'")
    # ### end Alembic commands ###
    pass
