"""Add detailImage FK for brands

Revision ID: caac58ce26e4
Revises: 5773efb242e6
Create Date: 2025-04-20 03:05:25.769783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caac58ce26e4'
down_revision: Union[str, None] = '5773efb242e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_images_brand_id", 'images', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_images_brand_id", 'images', type_='foreignkey')
    op.drop_column('images', 'brand_id')
    # ### end Alembic commands ###
