"""Add is anonymus to reviews

Revision ID: ffffc0c54a8c
Revises: cfe2db0f6915
Create Date: 2025-03-10 07:56:47.838722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffffc0c54a8c'
down_revision: Union[str, None] = 'cfe2db0f6915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_reviewer_anonymous', sa.Boolean(), nullable=True))
    op.execute("UPDATE reviews SET is_reviewer_anonymous = false")
    op.alter_column('reviews', 'is_reviewer_anonymous', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_reviewer_anonymous')
    # ### end Alembic commands ###
