export enum Pathnames {
  Login = "/login",
  SignUp = "/signup",
  Home = "",
  Social = "/social",
  CreateSocial = "/social/create",
  User = "/user",
  CreateUser = "/user/create",
  Channel = "/channel",
  CreateChannel = "/channel/create",
  EditChannel = "/channel/edit",
  Brand = "/brand",
  CreateBrand = "/brand/create",
  EditBrand = "/brand/edit",
  Host = "/host",
  Landing = "/landing",
  Submission = "/submission",
}
