// User
export const GET_USERS = "GET_USERS";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_GROUPS = "GET_USER_GROUPS";
export const GET_USERS_NOT_IN_GROUP = "GET_USERS_NOT_IN_GROUP";
export const JOIN_CHANNEL = "JOIN_CHANNEL";
export const DELETE_CHANNEL = "DELETE_CHANNEL";

// Channel
export const GET_CHANNELS = "GET_CHANNELS";
export const GET_CHANNELS_BY_ID = "GET_CHANNELS_BY_ID";

export const GET_SEARCH_GAMES = "GET_SEARCH_GAMES";

export const GET_GROUP_BY_ID = "GET_GROUP_BY_ID";
export const GET_SERACH_GROUPS = "GET_SERACH_GROUPS";
export const GET_SURVEY_RESPONSES = "GET_SURVEY_RESPONSES";

// Brand
export const GET_BRANDS = "GET_BRANDS";
export const GET_BRAND_BY_ID = "GET_BRAND_BY_ID";
export const GET_BRAND_REVIEW_LIST = "GET_BRAND_REVIEW_LIST";
export const BRAND_REVIEWS = "BRAND_REVIEWS";

// questionCardCategory
export const GET_QUESTION_CATEGORIES = "GET_QUESTION_CATEGORIES";
export const GET_QUESTION_CARDS = "GET_QUESTION_CARDS";

// brading
export const GET_REGISTER_LIST = "GET_REGISTER_LIST";
export const GET_SURVEYS = "GET_SURVEYS";
export const GET_SURVEY_BY_ID = "GET_SURVEY_BY_ID";

// hostRegistAdmin
export const GET_HOST_REGIST_ADMIN = "GET_HOST_REGIST_ADMIN";
export const GET_MY_HOST_REGIST = "GET_MY_HOST_REGIST";

export const GET_MAIN_IMAGE = "GET_MAIN_IMAGE";
export const GET_GALLERY_IMAGES = "GET_GALLERY_IMAGES";
