// landing
export const GET_SURVEYS = "GET_SURVEYS";
export const GET_LANDING_BRAND = "GET_LANDING_BRAND";
export const GET_LANDING_BRANDS = "GET_LANDING_BRANDS";
export const GET_LANDING_CHANNELS = "GET_LANDING_CHANNELS";

export const GET_MAIN_IMAGE = "GET_MAIN_IMAGE";
export const GET_GALLERY_IMAGES = "GET_GALLERY_IMAGES";
